version: "1"

services:
  app:
    ports:
      - "8080:8080"
    image: 'cloud-native-dev:latest'
    build:
      context: .
    container_name: cloud-native-dev
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud-native-db
      - SPRING_DATASOURCE_USERNAME=cloud-native-db
      - SPRING_DATASOURCE_PASSWORD=cloud-native-db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=cloud-native-db
      - POSTGRES_PASSWORD=cloud-native-db