name: Release pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Code Analysis
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=CNSD-minor-NelisRiebezos \
          -Dsonar.host.url=https://sonar.cloud-native-minor.it \
          -Dsonar.login=5e6febbebbd5841356745b865c2c685bb70acb43

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag account-service:v$GITHUB_RUN_NUMBER

      - name: Tag the build version
        run: |
          git tag "Build-v$GITHUB_RUN_NUMBER"
          git push origin "Build-v$GITHUB_RUN_NUMBER"